server:
  port: 8083

spring:
  cloud:
    gateway:
      routes:
        - id: memberServiceAPI
          uri: http://localhost:8080
          predicates:
            - Path=/api/member/**

        - id: loginServiceAPI
          uri: http://localhost:8080
          predicates:
            - Path=/login

        - id: mailServiceAPI
          uri: http://localhost:8080
          predicates:
            - Path=/api/mail/**

        - id: activityServiceAPI
          uri: http://localhost:8081
          predicates:
            - Path=/api/activities/**

        - id: newsFeedServiceAPI
          uri: http://localhost:8082
          predicates:
            - Path=/api/newsFeed/**
  main:
    web-application-type: reactive

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.server: DEBUG
